[package]

name = "multi_array"
version = "0.0.1"
authors = ["Sean Patrick Santos <SeanPatrickSantos@gmail.com>"]
description = "Multidimensional arrays for Rust."
readme = "README.md"
license = "Apache-2.0"
